KamikazeTrungThanh.Web/Controllers/ContactController.cs
using KamikazeTrungThanh.Common;
using KamikazeTrungThanh.Model.Models;
using KamikazeTrungThanh.Service;
using KamikazeTrungThanh.Web.Infrastructure.Extensions;
using KamikazeTrungThanh.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KamikazeTrungThanh.Web.Controllers
{
    public class ContactController : Controller
    {
        private IContactDetailService _contactDetailService;
        private IFeedbackService _feedbackService;

        public ContactController(IContactDetailService contactService, IFeedbackService feedbackService)
        {
            _contactDetailService = contactService;
            _feedbackService = feedbackService;
        }
        private ContactDetailViewModel GetDetail()
        {
            var modelData = _contactDetailService.GetDefaultContact();
            var viewModelResponseData = AutoMapper.Mapper.Map<ContactDetail, ContactDetailViewModel>(modelData);
            return viewModelResponseData;
        }
        // GET: Contact
        public ActionResult Index()
        {
            FeedbackViewModel viewModelFeedbackResponseData = new FeedbackViewModel();
            viewModelFeedbackResponseData.ContactDetail = GetDetail();
            return View(viewModelFeedbackResponseData);
        }

        public ActionResult SendFeedback(FeedbackViewModel feedbackViewModel)
        {
            if (ModelState.IsValid)
            {
                Feedback newFeedback = new Feedback();
                newFeedback.UpdateFeedback(feedbackViewModel);
                _feedbackService.Create(newFeedback);
                _feedbackService.Save();

                ViewData["SuccessMsg"] = "Gửi phản hồi thành công";
                string content = System.IO.File.ReadAllText(Server.MapPath("/Assets/client/template/contact_template.html"));
                content = content.Replace("{{Name}}", feedbackViewModel.Name);
                content = content.Replace("{{Email}}", feedbackViewModel.Email);
                content = content.Replace("{{Message}}", feedbackViewModel.Message);

                var adminEmail = ConfigHelper.GetByKey("AdminEmail");
                MailHelper.SendMail(adminEmail, "Nội dung phản hồi", content);

                feedbackViewModel.Name = "";
                feedbackViewModel.Email = "";
                feedbackViewModel.Message = "";

            }
            feedbackViewModel.ContactDetail = GetDetail();
            return View("Index",feedbackViewModel);
        }
    }
}

KamikazeTrungThanh.Web/Views/Contact/Index.cshtml
@model KamikazeTrungThanh.Web.Models.FeedbackViewModel
@{
    ViewBag.Title = "Contact Index";
    Layout = "~/Views/Shared/Layouts.cshtml";
}

@section FooterJS{
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBY9-9EcRD3c0dL6gsT_Dd5Y4mlbW2Vgp0"></script>

    <script src="~/Assets/client/js/controllers/Contact.js"></script>
}

<input type="hidden" id="hidAddress" value="@Model.ContactDetail.Name<br />Điện thoại: @Model.ContactDetail.Phone <br>Địa chỉ: @Model.ContactDetail.Address" />
<input type="hidden" id="hidLat" value="@Model.ContactDetail.Lat" />
<input type="hidden" id="hidLng" value="@Model.ContactDetail.Lng" />
<input type="hidden" id="hidName" value="@Model.ContactDetail.Name" />

<!-- contact -->
<div class="content-wrapper container">
    <div class="content-wrapper-top">
        <h4>Liên hệ với TRUNG THANH</h4>
        <div class="clearfix"> </div>
    </div>
    <div class="content-wrapper-row">
        <div class="contact-agile">
            <div id="map"></div>
            <div class="faq">
                <h4 class="latest-text">Thông tin liên hệ</h4>
                <div class="row contact-us">
                    <div class="col-md-3 location-agileinfo">
                        <div class="icon-w3">
                            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                        </div>
                        <h3>Address</h3>
                        <h4>@Model.ContactDetail.Address</h4>
                    </div>
                    <div class="col-md-3 call-agileits">
                        <div class="icon-w3">
                            <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
                        </div>
                        <h3>Call</h3>
                        <h4>@Model.ContactDetail.Phone</h4>
                    </div>
                    <div class="col-md-3 mail-wthree">
                        <div class="icon-w3">
                            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                        </div>
                        <h3>Email</h3>
                        <h4><a href="@Model.ContactDetail.Email">@Model.ContactDetail.Email</a></h4>
                    </div>
                    <div class="col-md-3 social-w3l">
                        <div class="icon-w3">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </div>
                        <h3>Social media</h3>
                        <ul>
                            <li><a href="https://www.facebook.com/"><i class="fa fa-facebook" aria-hidden="true"></i><span class="text">Facebook</span></a></li>

                            <li class="ggp"><a href="https://mail.google.com/mail/"><i class="fa fa-google-plus" aria-hidden="true"></i><span class="text">Google+</span></a></li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="row contact-us">
                    @using (Html.BeginForm("SendFeedback", "Contact", FormMethod.Post))
                    {

                        @Html.ValidationSummary(false, "", new { @class = "error" })
                        <div class="control-group form-group">
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Name, new { @class = "textbox form-control", @placeholder = "Họ và Tên", @required = "" })
                            </div>
                        </div>

                        <div class="control-group form-group">
                            <div class="controls">

                                @Html.TextBoxFor(model => model.Email, new { @class = "textbox form-control", @placeholder = "Email", @required = "" })
                            </div>
                        </div>
                        <div class="control-group form-group">
                            <div class="controls">

                                @Html.TextAreaFor(model => model.Message, new { @class = "form-control", @placeholder = "Nội dung phản hồi", @required = "" })
                            </div>
                        </div>

                        if (ViewData["SuccessMsg"] != null)
                        {
                            <div class="alert alert-success" role="alert">
                                <strong>Chúc mừng bạn! </strong> gửi phản hồi thành công.
                                <br />Chúng tôi sẽ liên hệ lại sớm nhất có thể.
                            </div>
                        }

                        <input type="submit" value="Gửi phản hồi">
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Map-JavaScript -->
@*<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
    <script type="text/javascript">
        google.maps.event.addDomListener(window, 'load', init);
        function init() {
            var mapOptions = {
                zoom: 11,
                center: new google.maps.LatLng(40.6700, -73.9400),
                styles: [{ "featureType": "all", "elementType": "labels.text.fill", "stylers": [{ "saturation": 36 }, { "color": "#000000" }, { "lightness": 40 }] }, { "featureType": "all", "elementType": "labels.text.stroke", "stylers": [{ "visibility": "on" }, { "color": "#000000" }, { "lightness": 16 }] }, { "featureType": "all", "elementType": "labels.icon", "stylers": [{ "visibility": "off" }] }, { "featureType": "administrative", "elementType": "geometry.fill", "stylers": [{ "color": "#000000" }, { "lightness": 20 }] }, { "featureType": "administrative", "elementType": "geometry.stroke", "stylers": [{ "color": "#000000" }, { "lightness": 17 }, { "weight": 1.2 }] }, { "featureType": "landscape", "elementType": "geometry", "stylers": [{ "color": "#000000" }, { "lightness": 20 }] }, { "featureType": "poi", "elementType": "geometry", "stylers": [{ "color": "#000000" }, { "lightness": 21 }] }, { "featureType": "road.highway", "elementType": "geometry.fill", "stylers": [{ "color": "#000000" }, { "lightness": 17 }] }, { "featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{ "color": "#000000" }, { "lightness": 29 }, { "weight": 0.2 }] }, { "featureType": "road.arterial", "elementType": "geometry", "stylers": [{ "color": "#000000" }, { "lightness": 18 }] }, { "featureType": "road.local", "elementType": "geometry", "stylers": [{ "color": "#000000" }, { "lightness": 16 }] }, { "featureType": "transit", "elementType": "geometry", "stylers": [{ "color": "#000000" }, { "lightness": 19 }] }, { "featureType": "water", "elementType": "geometry", "stylers": [{ "color": "#000000" }, { "lightness": 17 }] }]
            };
            var mapElement = document.getElementById('map');
            var map = new google.maps.Map(mapElement, mapOptions);
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(40.6700, -73.9400),
                map: map,
            });
        }
    </script>*@
<!-- //Map-JavaScript -->
<!-- //contact -->