KamikazeTrungThanh.Web/Controllers/PortfolioController.cs
using KamikazeTrungThanh.Model.Models;
using KamikazeTrungThanh.Service;
using KamikazeTrungThanh.Web.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace KamikazeTrungThanh.Web.Controllers
{
    public class PortfolioController : Controller
    {
        private IProductCategoryService _productCategoryService;
        private IProductService _productService;
        private ICommonService _commonService;
        public string aliasDefault = "mai-xep-di-dong";
        public int idDefault = 0;
        public string DefaultOrIndex = "default";

        public PortfolioController(IProductCategoryService productCategoryService, IProductService productService, ICommonService commonService)
        {
            _productCategoryService = productCategoryService;
            _productService = productService;
            _commonService = commonService;
        }

        public ActionResult Layouts(string alias, int id)
        {
            aliasDefault = alias;
            idDefault = id;

            ViewBag.aliasDefault = aliasDefault;
            ViewBag.idDefault = idDefault;

            return View();
        }

        [ChildActionOnly]
        public ActionResult Default(string alias)
        {
            if (!string.IsNullOrEmpty(alias)) aliasDefault = alias;
            var modelData = _productService.GetAllByAlias(aliasDefault);
            var viewModelData = AutoMapper.Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(modelData);

            return PartialView(viewModelData);
        }

        // GET: Portfolio

        [HttpPost]
        public ActionResult Index(string aliasProductCategory)
        {
            if (!string.IsNullOrEmpty(aliasProductCategory))
            {
                aliasDefault = aliasProductCategory;
                //aliasDefault = Request["aliasProductCategory"].ToString();
            }

            var modelData = _productService.GetAllByAlias(aliasDefault);
            var viewModelData = AutoMapper.Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(modelData);
            ViewBag.aliasDefault = aliasDefault;
            return PartialView(viewModelData);
        }

        [HttpPost]
        public ActionResult Detail(string alias, string aliasCategory, int id)
        {
            ViewBag.aliasDefault = aliasDefault;
            ViewBag.aliasCategory = aliasCategory;
            var productModel = _productService.GetById(id);
            var viewModelData = AutoMapper.Mapper.Map<Product, ProductViewModel>(productModel);
            List<string> moreImages = new JavaScriptSerializer().Deserialize<List<string>>(viewModelData.MoreImages);
            ViewBag.moreImages = moreImages;
            return View(viewModelData);
        }

        [ChildActionOnly]
        public ActionResult ProductCategoryPartialView(string ikeyword)
        {
            string keyword = ikeyword;
            var modelData = _commonService.GetNavigationMenuChild(keyword);
            var viewModelData = AutoMapper.Mapper.Map<IEnumerable<ProductCategory>, IEnumerable<ProductCategoryViewModel>>(modelData);
            return PartialView(viewModelData);
        }

        [ChildActionOnly]
        public ActionResult ProductHeaderPartialView(string alias)
        {
            aliasDefault = alias;
            var productCategoryBreadcrumb = _productCategoryService.GetByAlias(aliasDefault);
            var listBreadcrumb = _commonService.GetBreadcrumb(productCategoryBreadcrumb.ID);
            ViewBag.listBreadcrumb = AutoMapper.Mapper.Map<IEnumerable<ProductCategory>, IEnumerable<ProductCategoryViewModel>>(listBreadcrumb);
            return PartialView();
        }

        [ChildActionOnly]
        public ActionResult Bottom()
        {
            var modelData = _productCategoryService.GetTopProductCategory(8);
            var modelViewResponseData = AutoMapper.Mapper.Map<IEnumerable<ProductCategory> ,IEnumerable<ProductCategoryViewModel>>(modelData);
            return PartialView(modelViewResponseData);
        }
    }
}

KamikazeTrungThanh.Web/Views/Portfolio/Default.cshtml
@model IEnumerable<KamikazeTrungThanh.Web.Models.ProductViewModel>
@{ 
    var aliasDefault = "mai-xep-di-dong";
}
<div class="product-w3ls-right">
    @{ Html.RenderAction("ProductHeaderPartialView", "Portfolio");}
    <div class="products-row">
        @if (Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <div class="col-md-4 product-grids">
                    <div class="agile-products">
                        <div class="new-tag"><h6>new<br>Hot !!!</h6></div>
                        <a href="#" class="last-portfolio" data-url="@item.Alias" data-id="@item.ID" data-category="@aliasDefault"><img src="@item.Image" class="img-responsive" alt="img"></a>
                        <div class="agile-product-text">
                            <h5><a href="#" class="last-portfolio" data-url="@item.Alias" data-id="@item.ID" data-category="@aliasDefault">@item.Name</a></h5>
                            <a href="#" class="last-portfolio w3ls-cart pw3ls-cart" data-url="@item.Alias" data-id="@item.ID" data-category="@aliasDefault"><i class="fa fa-list" aria-hidden="true"></i> Xem chi tiết</a>
                            @*<h6><del>$200</del> $100</h6>*@

                        </div>
                    </div>
                </div>
            }
        }

        <div class="clearfix"> </div>
    </div>

</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(".last-portfolio").click(function (e) {
            e.preventDefault();
            $("#product").html("");
            var aliasPortfolio = $(this).attr("data-url");
            var idPortfolio = $(this).attr("data-id");
            var aliasCategory = $(this).attr("data-category");
            $.ajax({
                async: true,
                url: '@Url.Action("Detail","Portfolio")',

                data: {
                    'alias': aliasPortfolio,
                    'id': idPortfolio,
                    'aliasCategory': aliasCategory
                },
                type: "POST",
                success: function (data) {
                    console.log("co data tai detail = ");
                    $("#product").html(data);
                },
                error: function (xhr) {
                    alert(xhr);
                }
            });
        });

    });
</script>

KamikazeTrungThanh.Web/Views/Portfolio/Detail.cshtml
@model KamikazeTrungThanh.Web.Models.ProductViewModel
@{
    var aliasDefault = (string)ViewBag.aliasDefault;
    var aliasCategory = (string)ViewBag.aliasCategory;
    var moreImages = (List<string>)ViewBag.moreImages;
    var countImage = 0;
}
@section SlideJS{

    <script src="~/Assets/client/js/jquery.flexisel.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $("#flexiselDemo1").flexisel({
                visibleItems: 4,
                animationSpeed: 1000,
                autoPlay: true,
                autoPlaySpeed: 3000,
                pauseOnHover: true,
                enableResponsiveBreakpoints: true,
                responsiveBreakpoints: {
                    portrait: {
                        changePoint: 480,
                        visibleItems: 1
                    },
                    landscape: {
                        changePoint: 640,
                        visibleItems: 2
                    },
                    tablet: {
                        changePoint: 768,
                        visibleItems: 3
                    }
                }
            });

        });
    </script>
}


<div class="product-w3ls-right">
    @{ Html.RenderAction("ProductHeaderPartialView", "Portfolio", new { alias = aliasCategory });}
    <div class="products-row">
    
        <div class="col-md-12 portfolio_summary">
            <br />
            <div class="row">
                <div class="col-md-8">
                    <div id="carousel-example-generic" class="carousel slide picture_border" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">

                            @foreach (var item in moreImages)
                            {
                                countImage = countImage + 1;
                                if (countImage == 1)
                                {

                                    <li data-target="#carousel-example-generic" data-slide-to="@countImage" class="active"></li>
                                }
                                else
                                {
                                    <li data-target="#carousel-example-generic" data-slide-to="@countImage" class=""></li>
                                }

                            }


                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">

                            @{
                                countImage = 0;
                            }
                            @foreach (var itemSlide in moreImages)
                            {

                                if (countImage == 0)
                                {
                                    countImage = countImage + 1;
                                    <div class="item active">
                                        <img class="img-responsive" src="@itemSlide" title="@Model.Name">
                                    </div>
                                }
                                else
                                {
                                    <div class="item">
                                        <img class="img-responsive" src="@itemSlide" title="@Model.Name">
                                    </div>
                                }

                            }

                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="portfolio_summary_title">Thông tin chi tiết</p>
                    <span class="portfolio_summary_title_detail">
                        <strong>Cơ sở Trung Thanh</strong>
                        <br />
                        <strong>Sản phẩm: </strong> @Model.Name
                        <br />
                        <strong>Hotline: </strong> 0908.999.623
                        <br />
                        <strong>Email: </strong> inbaobitt@gmail.com
                        <br />
                        <strong>Xưởng lắp đặt: </strong> C5/1B Đường Nữ Dân Công, Bình Chánh, TP.HCM
                    </span>
                    
                </div>
            </div>
           
           
            <br />
            <div class="portfolio_summary_content">
                <span>
                     @Html.Raw(@Model.Content)
                </span>

            </div>
        </div>


         
        <div class="clearfix"> </div>
    </div>

</div>

KamikazeTrungThanh.Web/Views/Portfolio/Index.cshtml
@model IEnumerable<KamikazeTrungThanh.Web.Models.ProductViewModel>
@{ 
    var aliasDefault = (string)ViewBag.aliasDefault;
}
<div class="product-w3ls-right">
    @{ Html.RenderAction("ProductHeaderPartialView", "Portfolio",new { alias = aliasDefault});}
    <div class="products-row">
        @if (Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <div class="col-md-4 product-grids">
                    <div class="agile-products">
                        <div class="new-tag"><h6>new<br>Hot !!!</h6></div>
                        <a href="#" class="last-portfolio" data-url="@item.Alias" data-id="@item.ID" data-category="@aliasDefault"><img src="@item.Image" class="img-responsive" alt="img"></a>
                        <div class="agile-product-text">
                            <h5><a href="#" class="last-portfolio" data-url="@item.Alias" data-id="@item.ID" data-category="@aliasDefault">@item.Name</a></h5>
                            <a href="#" class="last-portfolio w3ls-cart pw3ls-cart" data-url="@item.Alias" data-id="@item.ID" data-category="@aliasDefault"><i class="fa fa-list" aria-hidden="true"></i> Xem chi tiết</a>
                            @*<h6><del>$200</del> $100</h6>*@
                            
                        </div>
                    </div>
                </div>
            }
        }

        <div class="clearfix"> </div>
    </div>

</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(".last-portfolio").click(function (e) {
            e.preventDefault();
            $("#product").html("");
            var aliasPortfolio = $(this).attr("data-url");
            var idPortfolio = $(this).attr("data-id");
            var aliasCategory = $(this).attr("data-category");
            $.ajax({
                async: true,
                url: '@Url.Action("Detail","Portfolio")',

                data: {
                    'alias': aliasPortfolio,
                    'id': idPortfolio,
                    'aliasCategory': aliasCategory
                },
                type: "POST",
                success: function (data) {
                    console.log("co data tai detail = ");
                    $("#product").html(data);
                },
                error: function (xhr) {
                    alert(xhr);
                }
            });
        });

    });
</script>

KamikazeTrungThanh.Web/Views/Portfolio/Layouts.cshtml
@{
    ViewBag.Title = "Portfolio Index";
    Layout = "~/Views/Shared/Layouts.cshtml";

   
    var aliasDefault = (string)ViewBag.aliasDefault;
    var idDefault = (int)ViewBag.idDefault;

}

<div class="products container">
    <div class="row">


        @{ Html.RenderAction("ProductCategoryPartialView", "Portfolio", new { ikeyword = "portfolio" });}

        <div id="product" class="col-md-9">

            @{Html.RenderAction("Default", "Portfolio", new { alias = aliasDefault }); }

        </div>

        <div class="clearfix"> </div>
    </div>
    <!-- recommendations -->
    @{ Html.RenderAction("Bottom", "Portfolio");}
    <!-- //recommendations -->
  
    <div class="clearfix"></div>
</div>

KamikazeTrungThanh.Web/Views/Portfolio/ProductCategoryPartialView.cshtml
@model IEnumerable<KamikazeTrungThanh.Web.Models.ProductCategoryViewModel>
@{ 
    
}

    
    <div class="col-md-3">
        <div class="product-top">
            <h4> Danh mục sản phẩm</h4>
        </div>
        <div class="rsidebar-top">
            <div class="sidebar-row">
                
                <ul class="faq">
                    @foreach (var item in Model)
                    {
                        if (item.Description.Contains("end"))
                        {
                            var flag = false;
                            foreach (var sub in Model)
                            {
                                if (item.ParentID == sub.ID)
                                {
                                    flag = true;
                                }
                            }
                            if (flag == true)
                            {

                            }
                            else
                            {
                                
                                <li class="item1">
                                    <a href="" class="last-item" data-url="@item.Alias">
                                        @item.Name
                                    </a>
                                </li>
                            }

                        }
                        else
                        {
                            <li class="item1">
                                <a href="#" class="item-menu">
                                    @item.Name
                                    <span class="glyphicon glyphicon-menu-down"></span>
                                </a>

                                <ul>
                                    @foreach (var sub in Model)
                                    {
                                        if (item.ID == sub.ParentID)
                                        {
                                           
                                            <li class="subitem1">
                                                <a href="" class="last-item" data-url="@sub.Alias">
                                                    @sub.Name
                                                </a>
                                            </li>
                                        }
                                    }
                                </ul>
                            </li>


                        }

                    }

                </ul>

            </div>

        </div>
        @{ 
            var UrlCare = "/portfolio-"+Model.FirstOrDefault().Alias+"-"+Model.FirstOrDefault().ID+".html" ;
        }
        <div class="related-row">
            <h4>Bạn quan tâm</h4>
            <div class="galry-like">
                <a href="@UrlCare"><img src="@Model.FirstOrDefault().Image" class="img-responsive" alt="img"></a>
                <br />
                <h4><a href="@UrlCare">@Model.FirstOrDefault().Name</a></h4>
                
            </div>
        </div>
    </div>

<!-- script for tabs -->
<script type="text/javascript">
        $(function () {

            var menu_ul = $('.faq > li > ul'),
                    menu_a = $('.faq > li > a');

            menu_ul.hide();

            menu_a.click(function (e) {

                if (!$(this).hasClass('active')) {
                    menu_a.removeClass('active');
                    menu_ul.filter(':visible').slideUp('normal');
                    $(this).addClass('active').next().stop(true, true).slideDown('normal');
                } else {
                    $(this).removeClass('active');
                    $(this).next().stop(true, true).slideUp('normal');
                }

                e.preventDefault();
            });

        });

        $(document).ready(function () {
            $(".last-item").click(function (e) {
                e.preventDefault();
                $("#product").html("");
                var aliasProductCategory = $(this).attr("data-url");
                console.log("alias = "+ aliasProductCategory);
                $.ajax({
                    async: true,
                    url: '@Url.Action("Index","Portfolio")',

                    data: { 'aliasProductCategory': aliasProductCategory },
                    type: "POST",
                    success: function (data) {
                        console.log("co data = ");
                        $("#product").html(data);
                    },
                    error: function (xhr) {
                        alert(xhr);
                    }
                });
            });


        });

</script>
<!-- script for tabs -->

KamikazeTrungThanh.Web/Views/Portfolio/ProductHeaderPartialView.cshtml
@{ 
    var listBreadcrumb = (IEnumerable<KamikazeTrungThanh.Web.Models.ProductCategoryViewModel>)ViewBag.listBreadcrumb;
    var TheEnd = listBreadcrumb.Count();
    var step = 0;
}
<!-- breadcrumbs -->
<ol class="breadcrumb breadcrumb1">
    @foreach (var item in listBreadcrumb)
    {
        step = step + 1;
        if (step != TheEnd)
        {
            <li><a href="index.html">@item.Name</a></li>
        }
        else
        {
            <li class="active">@item.Name</li>
        }
    }
    
    
</ol>
<div class="clearfix"> </div>
<!-- //breadcrumbs -->

<div class="product-top">
    <h4>@listBreadcrumb.Last().Name</h4>
    <div class="move-text">
        <div class="marquee">
            <a href="offers.html"> 
 
                    @Html.Raw(@listBreadcrumb.Last().MetaDescription)
         
            </a></div>
        <script src="~/Assets/client/js/jquery.marquee.min.js"></script>
        <script>
					  $('.marquee').marquee({ pauseOnHover: true });

        </script>
    </div>
    @*<ul>
            <li class="dropdown head-dpdn">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filter By<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Low price</a></li>
                    <li><a href="#">High price</a></li>
                    <li><a href="#">Latest</a></li>
                    <li><a href="#">Popular</a></li>
                </ul>
            </li>
        </ul>*@
    <div class="clearfix"> </div>
</div>